dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "thibaultfalque-github"
    token:
      secure: "$sonartoken"
jdk:
  - oraclejdk8
script:
  - mvn clean install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
